exports.countryFlagsMapper = {
    Russia: '🇷🇺',
    Ukraine: '🇺🇦',
    Belarus: '🇧🇾',
    Kazakhstan: '🇰🇿',
    Slovakia: '🇸🇰',
    Germany: '🇩🇪',
    Poland: '🇵🇱',
    Sweden: '🇸🇪',
    Finland: '🇫🇮',
    UK: '🇬🇧󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿',
    'United States': '🇺🇸',
    'United Kingdom': '🇬🇧',
    'UK & Europe': '🇬🇧 🇪🇺󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿',
    'USA & Europe': '🇺🇸 🇪🇺󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿',
    'UK, Europe & US': '🇬🇧 🇪🇺 🇺🇸󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿',
    'USA & Canada': '🇺🇸 🇨🇦󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿',
    Europe: '🇪🇺',
    Norway: '🇳🇴',
    Venezuela: '🇻🇪',
    Netherlands: '🇳🇱',
    Italy: '🇮🇪',
    Israel: '🇮🇱',
    'Czech Republic': '🇨🇿',
    Czechoslovakia: '🇨🇿',
    Iceland: '🇮🇸',
    Japan: '🇯🇵',
    US: '🇺🇸',
    Canada: '🇨🇦',
    'New Zealand': '🇳🇿',
    Australia: '🇦🇺',
    Austria: '🇦🇹',
    Spain: '🇪🇸',
    Belgium: '🇧🇪',
    Switzerland: '🇨🇭',
    France: '🇫🇷',
    Greece: '🇬🇷',
    Unknown: '❓',
    Worldwide: '🌍',
    International: '🌍',
    Mexico: '🇲🇽',
    Honduras: '🇭🇳',
    Brazil: '🇧🇷',
    China: '🇨🇳',
}

exports.bandStatusMapper = {
    'Changed name': 'Сменили название',
    Active: 'Активны',
    'Split-up': 'Распались',
    'Unknown': 'Неизвестно',
}